# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'PubstarAdsSwiftUIExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PubstarAdsSwiftUIExample
  pod 'Pubstar', :git => 'https://github.com/pubstar-io/PubStar-SDK-iOS.git', :branch => 'main'

end
